# Generated by Django 4.2 on 2025-06-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('event_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del Evento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('start_time', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha y Hora de Finalización')),
                ('is_paid_event', models.BooleanField(default=False, verbose_name='Evento Pagado')),
                ('total_tickets', models.IntegerField(default=0, verbose_name='Total de Tickets para el evento')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_categories.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEvent',
            fields=[
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='Actualizado el')),
                ('event_id', models.IntegerField(blank=True, db_index=True, verbose_name='ID del Evento')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('location', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('start_time', models.DateTimeField(verbose_name='Fecha y Hora de Inicio')),
                ('end_time', models.DateTimeField(verbose_name='Fecha y Hora de Finalización')),
                ('is_paid_event', models.BooleanField(default=False, verbose_name='Evento Pagado')),
                ('total_tickets', models.IntegerField(default=0, verbose_name='Total de Tickets para el evento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('company', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ticket_categories.company', verbose_name='Empresa')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Evento',
                'verbose_name_plural': 'historical Eventos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='EventTicketCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_available', models.IntegerField(default=0, verbose_name='Tickets asignados por categoría')),
                ('tickets_sold', models.PositiveIntegerField(default=0, verbose_name='Tickets vendidos')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ticket_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_categories.ticketcategory', verbose_name='Categoría ticket')),
            ],
            options={
                'verbose_name': 'Categoría de Ticket para Evento',
                'verbose_name_plural': 'Categorías de Tickets para Eventos',
                'unique_together': {('event', 'ticket_category')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_categories',
            field=models.ManyToManyField(through='events.EventTicketCategory', to='ticket_categories.ticketcategory'),
        ),
        migrations.AddField(
            model_name='event',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
