# Generated by Django 4.2 on 2025-06-15 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('ticket_categories', '0001_initial'),
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('attendee_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombres Asistente')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('Pasaporte', 'Pasaporte'), ('Carné de Extranjería', 'Carné de Extranjería'), ('Otros', 'Otros')], default='DNI', max_length=50, verbose_name='Tipo documento')),
                ('document_number', models.CharField(max_length=100, verbose_name='Número Documento')),
                ('phone_number', models.CharField(max_length=100, verbose_name='Teléfono')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha Nacimiento')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='attachments.attachment', verbose_name='Recibo Compra')),
            ],
            options={
                'verbose_name': 'Asistente',
                'verbose_name_plural': 'Asistentes',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('buyer', models.CharField(max_length=255, verbose_name='Nombres Comprador')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('ticket_confirmed', models.BooleanField(default=False, verbose_name='Ticket Confirmado')),
                ('ticket_owner', models.BooleanField(default=False, verbose_name='Titular Ticket')),
                ('ticket_send_by_email', models.BooleanField(default=False, verbose_name='Ticket por correo')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.attendee', verbose_name='Asistente')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendees.purchase', verbose_name='Compra')),
            ],
            options={
                'verbose_name': 'Boleto',
                'verbose_name_plural': 'Boletos',
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='attendees',
            field=models.ManyToManyField(through='attendees.Ticket', to='attendees.attendee', verbose_name='Asistentes'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_categories.company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='ticket_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_categories.ticketcategory', verbose_name='Categoría Ticket'),
        ),
    ]
