# Generated by Django 4.2 on 2025-06-15 08:35

import apps.attachments.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ticket_categories', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado el')),
                ('attachment_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/%Y/%m/%d/', validators=[apps.attachments.models.validate_file_size, apps.attachments.models.validate_file_extension], verbose_name='Archivo')),
                ('name', models.CharField(max_length=255, verbose_name='Asunto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_categories.company', verbose_name='Empresa')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
            },
        ),
    ]
